<meta charset="utf-8">
<title>Carrinho</title>
<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
<script src="https://kit.fontawesome.com/d96ecac57c.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="lib/owlCarousel/dist/assets/owl.carousel.min.css">
<link rel="stylesheet" href="lib/owlCarousel/dist/assets/owl.theme.default.min.css">
<link rel="stylesheet" type="text/css" href="css/estilo.css">
<link rel="stylesheet" type="text/css" href="materialize/css/materialize.min.css">


<footer class="page-footer grey darken-3" style="margin-top: 160px;">
	<div class="container">
		<div class="row">
			<div class="col l6 s12">
				<h5>Sobre a Empresa</h5>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at lacus congue.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at lacus congue, suscipit elit nec, tincidunt orci.</p>
			</div>
			<div class="col l4 offset-l2 s12">
				<h5 class="white-text">Contatos</h5>
				<ul>
					<li><a class="grey-text text-lighten-3" href="#">Facebook</a></li>
					<li><a class="grey-text text-lighten-3" href="#">Twitter</a></li>
					<li><a class="grey-text text-lighten-3" href="#">Instagram</a></li>
				</ul>
			</div>


		</div>

		<div class="footer-copyright grey darken-4">
			<div class="container center-align">&copy; 2019 Holpe Model</div>
		</div>

	</footer>